### ISSUE TITLE
override configuratoin

### ISSUE THREAD

**Issue by fraank** [octopress/genesis-theme#44]
The documentation says: "Also you will be able to set theme configurations for each language. For example to configure theme settings for your German pages, you'd create a _plugins/theme/config_[lang].yml and add whatever settings you want to override."

I cannot reproduce this functionality even if the file "plugins/theme/config_de.yml" is loaded (jekyll breaks if file-format is wrong). On my testsystem I do this:

_config.yml:
```yml
my_var: "this is cool"
lang: de

gems:
  - octopress-multilingual
  - octopress-genesis-theme
```

plugins/theme/config_de.yml:
```yml
my_var: "dieses ist cool"
```

index.html:
```liquid
---
layout: default
lang: de
---
{{ site.my_var }}
```

The output is always "this is cool". For "de" it should be "dieses ist cool". Any suggestions?
